services:

  web:
    user: root
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
      - db_data:/rails/storage
    environment:
      RAILS_ENV: development

  updater:
    user: root
    volumes:
      - .:/rails
      - db_data:/rails/storage
    environment:
      RAILS_ENV: development
