services:

  web:
    user: root
    command: bash -c "bin/rails assets:precompile && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
      - db_data:/rails/storage
    environment:
      RAILS_ENV: production

  updater:
    user: root
    volumes:
      - .:/rails
      - db_data:/rails/storage
    environment:
      RAILS_ENV: production
